### ISSUE TITLE
`tests` folder is included in the wheel.

### ISSUE THREAD

**Issue by nrbnlulu** [koaning/mktestdocs#11]
This killed me I didn't realized why I import tests and something else is imported.
![image](https://user-images.githubusercontent.com/88795475/234771043-4a28e2a4-f105-475f-8ec0-e483c2919353.png)

**Comment by koaning** [comment]
Ah! Good point. Will have a look.

**Comment by koaning** [comment]
Just pushed a new version that should exclude these tests. You may want to drop the venv, but it should be fixed when you start anew. Sorry about that!

**Comment by nrbnlulu** [comment]
Thanks!
