### ISSUE TITLE
Bug in `grab_code_blocks`

### ISSUE THREAD

**Issue by lebrice** [koaning/mktestdocs#12]
https://github.com/koaning/mktestdocs/blob/799fc3513126841f74748588348d40682f07084c/mktestdocs/__main__.py#L98

I believe this should be `if line.strip().startswith("```")`, since `textwrap.dedent` doesn't remove the indent of all lines, just the leading indent.

**Comment by lebrice** [comment]
For example, this doesn't work:
```python


class Foo:
    """Some class with a header and a code block.

    ```
    assert False, "this should fail."
    ```
    
    """
```

**Comment by koaning** [comment]
Strange that this wasn't reported earlier. If you happen to have the time to write some unit tests and or a fix I'd appreciate it!

**Comment by david26694** [comment]
This should solve it: https://github.com/koaning/mktestdocs/pull/13. For some reason I can't add you as reviewer @koaning

**Comment by koaning** [comment]
One observation, mktestdocs will ignore codeblocks where no language is attached. So in the future I would write this instead:

````
```python
```
````

**Comment by koaning** [comment]
Making a new release now that should fix this. Once again thanks @david26694 !
