### ISSUE TITLE
mktestdocs ignores indented Python code blocks

### ISSUE THREAD

**Issue by FlorianWilhelm** [koaning/mktestdocs#14]
Hi @koaning, as always, awesome package and thanks for providing it, it's really helpful!

I'm using it in my [ultimate-notion](https://ultimate-notion.com/) project and realised that mktestdocs seems to ignore indented Python code blocks, that I use for instance within [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), e.g.

```markdown
!!! note

    All cells of a table are initialized with an empty string. Therefore, to delete the content of a cell,
    you need to assign an empty string, i.e. `''`. For instance, to delete the first row after the header:

    ```python
    table[1] = ('', '', '')
    ```
```

It would be awesome if there were an option so that I could also check the code within admonitions. Thank you!

**Comment by koaning** [comment]
Ah! Interesting, yeah I would agree this is within scope of the project. 

Set a reminder!

**Comment by koaning** [comment]
Just made a release and I used your code example as a unit test. It should all be fixed now. But feel free to report back in if something breaks. 

Fun fact, this issue actually reminded me that this package exist. I almost forgot about it and after checking ... it also seems like there are about 6000 downloads a month 😅 .

**Comment by FlorianWilhelm** [comment]
Thanks a lot Vincent, really appreciate it. I actually wonder why it doesn't even have more users, it's extremely helpful when you want to make sure that the code in your docs is still correct. How else would you check it automatically?

**Comment by koaning** [comment]
I think many people don't bother, and theres also a lot of folks who use sphinx which has its own doctest system I think. Could be wrong on both tho.
