### ISSUE TITLE
Licence in pypi

### ISSUE THREAD

**Issue by TomKaltofen** [koaning/mktestdocs#18]
Hello, would it be possible to add licence information into the package creation process?

E.g. like adding this to setup.py:

    license="Apache Software License 2.0",  # Specifies the license type
    license_files=["LICENSE"],  # Points to the license file in the project root

Then one can read it out via tools like pip-licences and make automatically sure that one is compliant to your licencing rules.

**Comment by koaning** [comment]
Done! Thanks for the suggestion.

**Comment by TomKaltofen** [comment]
Directly worked for me! Thank you very much!
