### ISSUE TITLE
Issue with collecting code blocks from class docstrings

### ISSUE THREAD

**Issue by lebrice** [koaning/mktestdocs#19]
Hello there @FlorianWilhelm and @koaning .

This might be related (or a duplicate?) of #14. 
I thought I also previously reported this issue in #12. but perhaps there was a regression somehow?

Here's a minimal reproducer:
```python
class Foo:
    """Some Foo docstring.

    Examples:

    ```python
    assert False, "should fail!"
    ```
    """

check_docstring(Foo)  # this should fail, but doesn't!
assert grab_code_blocks(Foo.__doc__, lang="python")  # list shouldn't be empty, but it is!
```

**Comment by lebrice** [comment]
The cause of the bug is the use of `textwrap.dedent` on the docstring. It only removes the leading indent, but since the first line has no leading indent, it keeps the indent in the rest of the docstring.

Ignoring the first line's indentation fixes this:
```python
docstring_lines = docstring.splitlines()
docstring = (
    docstring_lines[0] + "\n" + textwrap.dedent("\n".join(docstring_lines[1:]))
)
```
 
 I can make a PR for this tomorrow if you'd like. :)

**Comment by koaning** [comment]
PR: yes please! Don't forget to add unit test!

**Comment by lebrice** [comment]
Nevermind @koaning , it seems like I might have been using an older version. This seems fixed with the `format_docstring` function. Closing this.
